### ISSUE TITLE
crash when clicking E

### ISSUE THREAD

**Issue by VaporeonScripts** [42atomys/fabric-advancementinfo-reloaded#17] opened 2024-08-25 15:30 UTC
using this mod and opening inventory while in creative , causes game to crash, and "not enough crashes" reports this mod as responsible for the crash

**Comment by 42atomys** [comment] 2024-09-11 16:17
hi @VaporeonScripts, I can't reproduce this bug on my client, can you have the log to let me investigate more if advancement-reloaded are responsible or not please ?

**Comment by VaporeonScripts** [comment] 2024-09-11 16:19
I quitted fabric to use neoforge now,so I don't use it anymore

**Comment by 42atomys** [comment] 2024-09-11 16:27
Ok thanks for your report and your response, I close this issue, feel free to open another if needed !

Have a good day :)

**Closed as not planned by 42atomys** 2024-09-11 16:27 UTC
Labels: type/bug 🔥, state/wontfix.do ⛔️
